name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar o deploy manualmente clicando no botão no GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Executando Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Conectado ao servidor da DigitalOcean!"
            
            # Navegando para a pasta do projeto (supondo que ficará na home root)
            cd ~/proposal-ai
            
            # Baixando o código novo
            echo "Fazendo git pull da branch main..."
            git pull origin main
            
            # Reconstruindo os containers que tiveram modificação no código e subindo-os
            echo "Realizando build e restart dos conteineres em plano de fundo..."
            docker compose -f docker-compose.prod.yml up -d --build
            
            # Em casa de acúmulo de imagens antigas, limpamos caches sem quebrar os containers ativos
            docker image prune -f
            
            echo "🚀 Deploy finalizado com sucesso!"
